# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4691395760c3fcecdf6d5d41a0e91f75571aff5db653b811361021dc4fcbd92f4f0a6272fe962d87a46f1b9e543ffb2f79ae102c588df78c65dfa3d5a65902

test:
  secret_key_base: 514fa7f0eafd806e6812cfb70eb561983a13e53d2f8c0f4635584fe1b94c68d32739741ad7b76ba6f25e767429389054fb2023df036e6c8567d379732aa332c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
